server:
  port: 8080

STAT_SERVER_URL: http://localhost:9090

spring:
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emwDb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${DATABASE_PASSWORD:sa}

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction: INFO

---
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE