version: '3.1'

services:
  stats-server:
    build: ./stats-service/server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=sa

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    restart: always
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=sa

  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - stats-db
      - ewm-db
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/emwDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=emwDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root